# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_langchain',
                'doc_host': 'https://AviPeltz.github.io',
                'git_url': 'https://github.com/AviPeltz/nbdev_langchain',
                'lib_path': 'nbdev_langchain'},
  'syms': {'nbdev_langchain.core': {'nbdev_langchain.core.foo': ('core.html#foo', 'nbdev_langchain/core.py')}}}
