# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_langchain',
                'doc_host': 'https://AviPeltz.github.io',
                'git_url': 'https://github.com/AviPeltz/nbdev_langchain',
                'lib_path': 'nbdev_langchain'},
  'syms': { 'nbdev_langchain.ScrapeGPT': { 'nbdev_langchain.ScrapeGPT.ImageDatasetScraper': ( 'scrapegpt.html#imagedatasetscraper',
                                                                                              'nbdev_langchain/ScrapeGPT.py'),
                                           'nbdev_langchain.ScrapeGPT.ImageDatasetScraper.__init__': ( 'scrapegpt.html#imagedatasetscraper.__init__',
                                                                                                       'nbdev_langchain/ScrapeGPT.py'),
                                           'nbdev_langchain.ScrapeGPT.ImageDatasetScraper.__str__': ( 'scrapegpt.html#imagedatasetscraper.__str__',
                                                                                                      'nbdev_langchain/ScrapeGPT.py'),
                                           'nbdev_langchain.ScrapeGPT.ImageDatasetScraper.run': ( 'scrapegpt.html#imagedatasetscraper.run',
                                                                                                  'nbdev_langchain/ScrapeGPT.py')},
            'nbdev_langchain.cards': { 'nbdev_langchain.cards.Card': ('cards.html#card', 'nbdev_langchain/cards.py'),
                                       'nbdev_langchain.cards.Card.__init__': ('cards.html#card.__init__', 'nbdev_langchain/cards.py'),
                                       'nbdev_langchain.cards.Card.__str__': ('cards.html#card.__str__', 'nbdev_langchain/cards.py')},
            'nbdev_langchain.core': {'nbdev_langchain.core.foo': ('core.html#foo', 'nbdev_langchain/core.py')}}}
