# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_scrapeGPT.ipynb.

# %% auto 0
__all__ = ['ImageDatasetScraper']

# %% ../nbs/01_scrapeGPT.ipynb 8
class ImageDatasetScraper:
    "A scraper for images described by your `search`, that scrapes for `max_images` you define"
    def __init__(self, 
                 search:str,            # A prompt describing that classes you are searching for 
                 max_images:int): # The max number of images to scrape for
        self.search, self.max_images = search, max_images
    
    def __str__(self): return f"Search for: {self.search}\nMax number of images: {self.max_images}\n"
    __repr__ = __str__
    
    def run():
        pass
